export const imagesOperations = [
  {
    src: require ('../assets/photos/operations/1.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/2.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/3.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/4.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/5.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/6.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/7.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/8.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/9.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/11.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/12.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 800,
    height: 940,
  },
  {
    src: require ('../assets/photos/operations/13.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 800,
    height: 940,
  },
  {
    src: require ('../assets/photos/operations/14.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/15.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
];

export const imagesRK = [
  {
    src: require ('../assets/photos/rk/1.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/2.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/3.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/4.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/5.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/6.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 800,
    height: 940,
  },
  {
    src: require ('../assets/photos/rk/7.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/8.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/9.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/10.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/11.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
];

export const imagesLM = [
  {
    src: require ('../assets/photos/lm/1.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/2.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 800,
    height: 940,
  },
  {
    src: require ('../assets/photos/lm/3.jpg'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/4.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/5.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/6.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/7.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/8.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/9.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/11.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/12.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 800,
    height: 940,
  },
  {
    src: require ('../assets/photos/lm/13.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/14.JPG'),
    alt: "README.md",
    caption: "README.md",
    width: 1419,
    height: 800,
  },
];