export const imagesOperations = [
  {
    src: require ('../assets/photos/operations/1.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "OPERAČNÝ SÁL 1",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/2.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "OPERAČNÝ SÁL 1",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/3.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "OPERAČNÝ SÁL 1",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/4.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "OPERAČNÝ SÁL 1",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/5.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "OPERAČNÝ SÁL 1",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/6.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "OPERAČNÝ SÁL 2",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/7.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "OPERAČNÝ SÁL 2",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/8.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "OPERAČNÝ SÁL 2",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/9.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "OPERAČNÝ SÁL 2",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/11.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "POOPERAČNÉ LÔŽKO 1",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/12.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "POOPERAČNÉ LÔŽKO 1 - TOALETA",
    width: 800,
    height: 940,
  },
  {
    src: require ('../assets/photos/operations/13.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "POOPERAČNÉ LÔŽKO 1",
    width: 800,
    height: 940,
  },
  {
    src: require ('../assets/photos/operations/14.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "POOPERAČNÉ LÔŽKO 2",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/operations/15.JPG'),
    alt: "Ústredná vojenská nemocnica SNP Ružomberok",
    caption: "POOPERAČNÉ LÔŽKO 2",
    width: 1419,
    height: 800,
  },
];

export const imagesRK = [
  {
    src: require ('../assets/photos/rk/1.JPG'),
    alt: "ORTOREHAB KLINIKA RUŽOMBEROK",
    caption: "ČAKÁREŇ",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/2.JPG'),
    alt: "ORTOREHAB KLINIKA RUŽOMBEROK",
    caption: "AMBULANCIA 1",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/3.JPG'),
    alt: "ORTOREHAB KLINIKA RUŽOMBEROK",
    caption: "AMBULANCIA 2",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/4.JPG'),
    alt: "ORTOREHAB KLINIKA RUŽOMBEROK",
    caption: "DONZITOMETRIA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/5.JPG'),
    alt: "ORTOREHAB KLINIKA RUŽOMBEROK",
    caption: "DONZITOMETRIA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/6.JPG'),
    alt: "ORTOREHAB KLINIKA RUŽOMBEROK",
    caption: "REHABILIRAČNÁ AMBULANCIA",
    width: 800,
    height: 940,
  },
  {
    src: require ('../assets/photos/rk/7.JPG'),
    alt: "ORTOREHAB KLINIKA RUŽOMBEROK",
    caption: "REHABILIRAČNÁ AMBULANCIA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/8.JPG'),
    alt: "ORTOREHAB KLINIKA RUŽOMBEROK",
    caption: "REHABILIRAČNÁ AMBULANCIA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/9.JPG'),
    alt: "LEKÁREŇ ARONIA RUŽOMBEROK",
    caption: "",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/10.JPG'),
    alt: "LEKÁREŇ ARONIA RUŽOMBEROK",
    caption: "PREDAJŇA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/rk/11.JPG'),
    alt: "LEKÁREŇ ARONIA RUŽOMBEROK",
    caption: "PREDAJŇA",
    width: 1419,
    height: 800,
  },
];

export const imagesLM = [
  {
    src: require ('../assets/photos/lm/1.JPG'),
    alt: "ORTOREHAB KLINIKA LIPTOVSKÝ MIKULÁŠ",
    caption: "BUDOVA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/2.JPG'),
    alt: "ORTOREHAB KLINIKA LIPTOVSKÝ MIKULÁŠ",
    caption: "REHABILITAČNÁ AMBULANCIA 1",
    width: 800,
    height: 940,
  },
  {
    src: require ('../assets/photos/lm/4.JPG'),
    alt: "ORTOREHAB KLINIKA LIPTOVSKÝ MIKULÁŠ",
    caption: "REHABILITAČNÁ AMBULANCIA 1",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/3.jpg'),
    alt: "ORTOREHAB KLINIKA LIPTOVSKÝ MIKULÁŠ",
    caption: "REHABILITAČNÁ AMBULANCIA 2",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/5.JPG'),
    alt: "ORTOREHAB KLINIKA LIPTOVSKÝ MIKULÁŠ",
    caption: "DONZITOMETRIA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/6.JPG'),
    alt: "ORTOREHAB KLINIKA LIPTOVSKÝ MIKULÁŠ",
    caption: "ČAKÁREŇ",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/7.JPG'),
    alt: "ORTOREHAB KLINIKA LIPTOVSKÝ MIKULÁŠ",
    caption: "FYZIOTERAPEUTICKÁ AMBULANCIA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/8.JPG'),
    alt: "ORTOREHAB KLINIKA LIPTOVSKÝ MIKULÁŠ",
    caption: "VYŠETROVŇA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/9.JPG'),
    alt: "ORTOREHAB KLINIKA LIPTOVSKÝ MIKULÁŠ",
    caption: "VYŠETROVŇA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/11.JPG'),
    alt: "ORTOREHAB KLINIKA LIPTOVSKÝ MIKULÁŠ",
    caption: "VYŠETROVŇA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/12.JPG'),
    alt: "LEKÁREŇ MÁJ LIPTOVSKÝ MIKULÁŠ",
    caption: "",
    width: 800,
    height: 940,
  },
  {
    src: require ('../assets/photos/lm/13.JPG'),
    alt: "LEKÁREŇ MÁJ LIPTOVSKÝ MIKULÁŠ",
    caption: "PREDAJŇA",
    width: 1419,
    height: 800,
  },
  {
    src: require ('../assets/photos/lm/14.JPG'),
    alt: "LEKÁREŇ MÁJ LIPTOVSKÝ MIKULÁŠ",
    caption: "PREDAJŇA",
    width: 1419,
    height: 800,
  },
];